FROM php:7.2-fpm

# Type docker-php-ext-install to see available extensions
# RUN docker-php-ext-install pdo pdo_sqlite

RUN echo 'alias sf="php app/console"' >> ~/.bashrc \
&& echo 'alias sf3="php bin/console"' >> ~/.bashrc